fix linter

diff --git a/.github/workflows/clang-tidy-format.yml b/.github/workflows/clang-tidy-format.yml
--- a/.github/workflows/clang-tidy-format.yml
+++ b/.github/workflows/clang-tidy-format.yml
@@ -1,10 +1,9 @@
-# Workflow syntax:
-# https://help.github.com/en/articles/workflow-syntax-for-github-actions
 name: cpp-linter
 
 on:
   push:
-    paths-ignore: "docs/**"
+    paths-ignore: 
+      - "docs/**"
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
@@ -15,20 +14,21 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - name: Install clang
-        run: sudo apt install clang-11 --install-suggests
-      - uses: shenxianpeng/cpp-linter-action@master
-        id: linter
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          style: file
-          version: 11
-          files-changed-only: true
-          lines-changed-only: true
-          extensions: 'cc,hh'
-          tidy-checks: 'readability-identifier-naming'
-      - name: Fail fast?!
-        if: steps.linter.outputs.checks-failed > 0
-        run: exit 1
 
+      - name: Install clang-tidy
+        run: sudo apt-get install -y clang-tidy-11
+
+      - name: Run clang-tidy
+        run: |
+          find ./src -type f \( -name "*.cc" -o -name "*.hh" \) -exec clang-tidy-11 --checks='readability-*,performance-*,modernize-*' --warnings-as-errors='*' {} +
+
+      - name: Fail fast if clang-tidy reports errors
+        run: |
+          if grep -Rin "warning: " clang-tidy-report.txt; then
+            echo "Clang-tidy reported warnings!"
+            exit 1
+          fi
+          if grep -Rin "error: " clang-tidy-report.txt; then
+            echo "Clang-tidy reported errors!"
+            exit 1
+          fi
